#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	SML::Template;
	
	print "START\n";
	
	my	$source_filename	= 'data.sml';

	my	$template = new SML::Template();
	my	$text_source = qx{cat $source_filename};
		$template->parse( $text_source );

	print "PARSED\n";

	$template->{token_value}{title}	= 'titulek';
	$template->{token_value}{body}	= '<body id="my-body">';
	$template->{token_value}{text}	= '[text]';
	$template->{token_value}{para3}	= '[para3]';
	print $template->build();