#!/usr/bin/perl -w

	use strict;
	use warnings;
	use Data::Dump qw(pp);
	use	SML::Template;
	
	print "START\n";
	

	my	$template = new SML::Template();
	my	$text_source = '<meta name="template" content="token.node:element.replace:node"><node>';
		$template->parse( $text_source );

	print "PARSED\n";

	$template->set_token_value( node => "[inserted text value]\n" );
	print $template->build();